#!/usr/bin/env python3
"""
Distil photographs into what the device renders from.

v0.3 stores ONE thing per photograph: the image itself, in RGB565, at panel
resolution. Nothing is summarised.

Earlier versions stored a 256-entry median-cut histogram, which was a mistake:
median cut allocates its boxes by pixel mass, so a small saturated accent (the
orange shrine in the Bangkok greenery) collapsed into one or two entries and
came out as a contour line instead of a region. Then v0.2 stored the whole
pixel list pre-sorted by luminance, which fixed the colour but only worked for
a GLOBAL permutation.

v0.3 permutes LOCALLY -- inside cells whose size grows with the reduction dial
-- so the sort has to happen on the device, per cell, per frame. That needs the
pixels in their original positions, not pre-sorted. Luminance is derived at load
time rather than stored: it is a pure function of the pixel.

Cost: 320*240*2 = 150 kB per photograph in flash. Six photographs, 900 kB.

Usage:  python3 tools/import_images.py tools/src/*.png > images.h
"""

import sys, os
from PIL import Image, ImageOps
import numpy as np

W, H = 412, 412   # panel redondo Waveshare 1.46
PAL = 16


def prepare(path):
    im = Image.open(path)
    im = ImageOps.exif_transpose(im).convert("RGB")
    # centre crop to the panel's aspect, then resize
    tw, th = W / H, im.width / im.height
    if th > tw:
        nw = int(im.height * tw)
        im = im.crop(((im.width - nw) // 2, 0, (im.width + nw) // 2, im.height))
    else:
        nh = int(im.width / tw)
        im = im.crop((0, (im.height - nh) // 2, im.width, (im.height + nh) // 2))
    return im.resize((W, H), Image.LANCZOS)


def palette_of(im):
    """16 colours, dark to light. ONLY for UI chrome -- bars, text, swatches.
    The field itself never touches this."""
    q = im.quantize(colors=PAL, method=Image.MEDIANCUT, dither=Image.NONE)
    raw = q.getpalette()[: PAL * 3]
    cols = [tuple(raw[i * 3 : i * 3 + 3]) for i in range(PAL)]
    cols.sort(key=lambda c: 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2])
    return cols


def rgb565_of(im):
    a = np.asarray(im, dtype=np.uint16)
    r, g, b = a[..., 0], a[..., 1], a[..., 2]
    return (((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)).reshape(-1)


def emit(paths):
    names = [os.path.splitext(os.path.basename(p))[0] for p in paths]
    out = []
    out.append("// GENERATED by tools/import_images.py - do not edit by hand.")
    out.append("// Each field is the photograph itself, %dx%d, RGB565." % (W, H))
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("#define IMG_W %d" % W)
    out.append("#define IMG_H %d" % H)
    out.append("#define IMG_COUNT %d" % len(paths))
    out.append("")
    out.append("// Las fotografias se DEFINEN una sola vez, en la unidad de compilacion")
    out.append("// que define IMAGES_DEFINE (field.cpp). En las demas solo se declaran.")
    out.append("// Con `static const` cada .cpp que incluia esto se llevaba su propia")
    out.append("// copia: 2 MB de fotos ocupaban 4 MB de flash y el binario no cabia.")
    out.append("struct ImgField { const uint32_t *pal; const uint16_t *rgb; const char *source; };")
    out.append("#ifdef IMAGES_DEFINE")
    out.append("#define IMG_DEF")
    out.append("#else")
    out.append("#define IMG_DEF extern")
    out.append("#endif")
    out.append("")

    for name, path in zip(names, paths):
        im = prepare(path)
        cols = palette_of(im)
        rgb = rgb565_of(im)

        out.append("// --- %s ---" % name)
        out.append("#ifdef IMAGES_DEFINE")
        out.append("const uint32_t IMG_PAL_%s[16] = {" % name.upper())
        for i in range(0, 16, 8):
            out.append("  %s," % ", ".join("0x%02x%02x%02x" % c for c in cols[i : i + 8]))
        out.append("};")
        out.append("const uint16_t IMG_RGB_%s[IMG_W * IMG_H] = {" % name.upper())
        for i in range(0, rgb.size, 24):
            out.append("  " + ",".join("0x%04x" % v for v in rgb[i : i + 24]) + ",")
        out.append("};")
        out.append("#else")
        out.append("extern const uint32_t IMG_PAL_%s[16];" % name.upper())
        out.append("extern const uint16_t IMG_RGB_%s[IMG_W * IMG_H];" % name.upper())
        out.append("#endif")
        out.append("")

    out.append("#ifdef IMAGES_DEFINE")
    out.append("extern const ImgField IMAGES[IMG_COUNT] = {")   # extern: en C++ un const global es interno por defecto
    for name in names:
        out.append('  { IMG_PAL_%s, IMG_RGB_%s, "%s" },' % (name.upper(), name.upper(), name))
    out.append("};")
    out.append("#else")
    out.append("extern const ImgField IMAGES[IMG_COUNT];")
    out.append("#endif")
    return "\n".join(out)


if __name__ == "__main__":
    print(emit(sys.argv[1:]))
